### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by 20Sunny** [lolainta/NYCU-ML-2022-Fall#1]
I am currently learning the data mining, I also take a re-vision on your repo. Very helpful. 
this repo is recommended by the GOOGLE BARD
![Screenshot 2023-06-25 172744](https://github.com/lolainta/NYCU-ML-2022-Fall/assets/119580558/d44638a7-a110-4e72-a8ea-f31e9662f247)

**Comment by lolainta** [comment]
Hi,

You're welcome! I'm glad I could assist you. It was my pleasure to help. If you have any further questions or need any additional support, please feel free to reach out. I'll be happy to assist you.

Thanks again for your kind words!

Best regards,
LolaInTa
